In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [110]:
games = pd.read_csv('../Resources/game_info.csv')

In [111]:
games.head(2)

,id,slug,name,metacritic,released,tba,updated,website,rating,rating_top,...,developers,genres,publishers,esrb_rating,added_status_yet,added_status_owned,added_status_beaten,added_status_toplay,added_status_dropped,added_status_playing
0,1,dgeneration-hd,D/Generation HD,NaN,2015-10-23,False,2019-09-17T11:58:57,http://dgeneration.net,0.0,0,...,West Coast Software,Adventure||Puzzle,West Coast Software,Everyone 10+,4,88,2,2,0,0
1,10,g-prime,G Prime Into The Rain,NaN,2016-01-06,False,2019-11-06T23:04:19,NaN,0.0,0,...,Soma Games,Simulation||Indie,Immanitas Entertainment||Code-Monkeys,Everyone,2,42,2,0,0,0

In [112]:
games.shape

(474417, 27)

In [113]:
games.columns

Index(['id', 'slug', 'name', 'metacritic', 'released', 'tba', 'updated',
       'website', 'rating', 'rating_top', 'playtime', 'achievements_count',
       'ratings_count', 'suggestions_count', 'game_series_count',
       'reviews_count', 'platforms', 'developers', 'genres', 'publishers',
       'esrb_rating', 'added_status_yet', 'added_status_owned',
       'added_status_beaten', 'added_status_toplay', 'added_status_dropped',
       'added_status_playing'],
      dtype='object')

In [114]:
games = games[['id', 'name', 'released', 'developers','publishers']]

In [115]:
games.head(2)

,id,name,released,developers,publishers
0,1,D/Generation HD,2015-10-23,West Coast Software,West Coast Software
1,10,G Prime Into The Rain,2016-01-06,Soma Games,Immanitas Entertainment||Code-Monkeys

In [116]:
users = pd.read_csv('../Resources/user_info.csv')

In [117]:
users.shape

(980, 6)

In [118]:
users.head(3)

   User ID first_name last_name                email      gender  age
0        1  Zachariah   Hairyes    zhairyes0@epa.gov        Male   20
1        2       Doug   Minihan  dminihan1@cam.ac.uk  Non-binary   23
2        3     Yvonne     Kopps     ykopps2@live.com      Female   68

In [119]:
users = users[['User ID', 'email', 'age']]

In [120]:
users.head(3)

   User ID                email  age
0        1    zhairyes0@epa.gov   20
1        2  dminihan1@cam.ac.uk   23
2        3     ykopps2@live.com   68

In [121]:
ratings = pd.read_csv('../Resources/user_ratings.csv')

In [122]:
ratings.head(3)

   User ID  Game ID  Review Score
0      321   169419             7
1      971   315015             0
2      311   384685             4

In [123]:
games.rename(columns={
    "id":"Game ID"
}, inplace=True)

In [124]:
games.head(3)

,Game ID,name,released,developers,publishers
0,1,D/Generation HD,2015-10-23,West Coast Software,West Coast Software
1,10,G Prime Into The Rain,2016-01-06,Soma Games,Immanitas Entertainment||Code-Monkeys
2,100,Land Sliders,2015-09-24,Prettygreat Pty,Prettygreat Pty

In [125]:
ratings.shape

(979, 3)

In [126]:
ratings["User ID"].value_counts()

User ID
842    5
316    5
707    4
962    4
835    4
      ..
515    1
779    1
867    1
801    1
201    1
Name: count, Length: 630, dtype: int64

In [127]:
ratings['User ID'].unique().shape

(630,)

In [128]:
x = ratings["User ID"].value_counts() > 1
x

User ID
842     True
316     True
707     True
962     True
835     True
       ...
515    False
779    False
867    False
801    False
201    False
Name: count, Length: 630, dtype: bool

In [129]:
x[x].shape

(262,)

In [130]:
y = x[x].index
y

Index([842, 316, 707, 962, 835, 531, 186, 924, 512,  40,
       ...
       971, 311, 907, 711, 603,  87, 601, 339, 172, 116],
      dtype='int64', name='User ID', length=262)

In [131]:
ratings[ratings["User ID"].isin(y)]

     User ID  Game ID  Review Score
0        321   169419             7
1        971   315015             0
2        311   384685             4
3        907   235784             0
4        711   433699             0
..       ...      ...           ...
971      755    82248             9
972      531   371312             0
974      803   256644             0
977      548    57060             0
978      274   240456             0

[611 rows x 3 columns]

In [132]:
ratings.head()

   User ID  Game ID  Review Score
0      321   169419             7
1      971   315015             0
2      311   384685             4
3      907   235784             0
4      711   433699             0

In [133]:
ratings.shape

(979, 3)

In [134]:
ratings_games = ratings.merge(games, on = "Game ID")

In [135]:
ratings_games.head()

,User ID,Game ID,Review Score,name,released,developers,publishers
0,971,315015,0,Fluffensnuff,2019-04-30,bippinbits,NaN
1,311,384685,4,Mermaid Games - Makeover and Salon Game,2017-08-21,Armored Techno Solution,Armored Techno Solution
2,907,235784,0,三國志曹操傳－逐鹿中原,2017-08-04,zhang weibin,zhang weibin
3,711,433699,0,Fading Ember,2020-04-21,michaell308,NaN
4,23,217375,0,Real Monster Truck Driving,2017-11-07,BUI THI THUY DUNG,BUI THI THUY DUNG

In [136]:
ratings_games.shape

(873, 7)

In [137]:
number_of_ratings = ratings_games.groupby("name")["Review Score"].count().reset_index()

In [138]:
number_of_ratings.head()
#how many review scores does this game name have?

                                  name  Review Score
0  "Bounce Blast" Construct 3 Template             1
1                   "Optical illusion"             1
2                  "Revenge Of Heroes"             1
3                              /reroll             1
4                             10000000             1

In [139]:
number_of_ratings.rename(columns={"Review Score":"number of ratings"}, inplace=True)

In [140]:
number_of_ratings.head()

                                  name  number of ratings
0  "Bounce Blast" Construct 3 Template                  1
1                   "Optical illusion"                  1
2                  "Revenge Of Heroes"                  1
3                              /reroll                  1
4                             10000000                  1

In [141]:
finished_set = ratings_games.merge(number_of_ratings, on="name")

In [142]:
finished_set.head()

,User ID,Game ID,Review Score,name,released,developers,publishers,number of ratings
0,971,315015,0,Fluffensnuff,2019-04-30,bippinbits,NaN,1
1,311,384685,4,Mermaid Games - Makeover and Salon Game,2017-08-21,Armored Techno Solution,Armored Techno Solution,1
2,907,235784,0,三國志曹操傳－逐鹿中原,2017-08-04,zhang weibin,zhang weibin,1
3,711,433699,0,Fading Ember,2020-04-21,michaell308,NaN,1
4,23,217375,0,Real Monster Truck Driving,2017-11-07,BUI THI THUY DUNG,BUI THI THUY DUNG,1

In [143]:
finished_set.sample(10)

,User ID,Game ID,Review Score,name,released,developers,publishers,number of ratings
668,931,160615,0,Upload,2017-09-11,ZPhillipsGames,NaN,1
141,896,309840,0,Body Discovery,2019-04-29,medic-games,medic-games,1
702,978,450032,0,City Hunter (itch),2020-05-29,Prateeks3,NaN,1
229,540,45991,1,Galaxia Conquestum,NaN,Alien Octopus Studio,Alien Octopus Studio,1
12,515,98512,0,The Static,2018-08-06,Pol Clarissou,NaN,1
206,546,39275,3,Ran Online,2006-07-27,Min Communications,Min Communications,1
688,948,165290,0,Lunch Boxers,2017-12-06,spacesharkstudios,NaN,1
819,254,139399,0,The Vaccum,2016-10-09,BurningGoose,NaN,1
577,550,367980,0,Thrasher (hypercraft games),2019-08-19,hypercraft games,NaN,1
279,319,290338,0,Mul- Again,2019-02-03,TheSlothmeister,NaN,1

In [144]:
finished_set

,User ID,Game ID,Review Score,name,released,developers,publishers,number of ratings
0,971,315015,0,Fluffensnuff,2019-04-30,bippinbits,NaN,1
1,311,384685,4,Mermaid Games - Makeover and Salon Game,2017-08-21,Armored Techno Solution,Armored Techno Solution,1
2,907,235784,0,三國志曹操傳－逐鹿中原,2017-08-04,zhang weibin,zhang weibin,1
3,711,433699,0,Fading Ember,2020-04-21,michaell308,NaN,1
4,23,217375,0,Real Monster Truck Driving,2017-11-07,BUI THI THUY DUNG,BUI THI THUY DUNG,1
...,...,...,...,...,...,...,...,...
868,803,256644,0,Pumpkin Villain,2018-10-21,simeon.platonov,NaN,1
869,527,188202,2,SpaceSurvivor (Frickin'Pancake),2016-01-21,Frickin'Pancake,NaN,1
870,80,193243,9,LittleFlowerBigSky (PolarFox),2015-12-15,PolarFox,NaN,1
871,548,57060,0,Fever Pitch Soccer,1995-01-01,U.S. Gold,Atari||U.S. Gold,1
872,274,240456,0,World of Wolf Clans,2017-08-05,Andrew Kudrin,Andrew Kudrin,1

In [145]:
finished_set.shape

(873, 8)

In [146]:
games_pivot_table = finished_set.pivot_table(columns='User ID', index='name', values='Review Score')

In [147]:
games_pivot_table

User ID,1,5,6,7,8,10,11,13,14,15,...,965,966,967,968,969,970,971,972,976,978
name,,,,,,,,,,,,,,,,,,,,,
"""Bounce Blast"" Construct 3 Template",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Optical illusion""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Revenge Of Heroes""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
/reroll,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
三分鐘抗議團,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
三國志曹操傳－逐鹿中原,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
坦克塔防大作战手游之经典保卫英雄大战游戏,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
梦回神都,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
疯狂捕鱼电玩城,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [148]:
games_pivot_table.shape

(872, 600)

In [149]:
#Make Nan 0
games_pivot_table.fillna(0, inplace=True)

In [150]:
games_pivot_table.head(23)
#games_pivot_table['name'][0]

User ID,1,5,6,7,8,10,11,13,14,15,...,965,966,967,968,969,970,971,972,976,978
name,,,,,,,,,,,,,,,,,,,,,
"""Bounce Blast"" Construct 3 Template",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"""Optical illusion""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"""Revenge Of Heroes""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
/reroll,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
111 Winchester: From Song to Story,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123 Soleil!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2 Minutes for Roughing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20 000 pieds sous terre,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 & Balls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Games,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42 Lightyears,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5 Cards No Fingers,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5 Seconds Of Summer - Lie To Me - Piano Tiles Pc,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7-in-1 Brain Sharpness Bundle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8 minutes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
<< FIND REWIND,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A New Start!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A STICKMANS ADVENTURE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Show of Kindness,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Walk In The Park (cammySashimi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A cat with no tail,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A simple life,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [151]:
#0 is ignored in distance calculation
from scipy.sparse import csr_matrix

In [152]:
games_sparse_mx = csr_matrix(games_pivot_table)

In [153]:
games_sparse_mx

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 280 stored elements and shape (872, 600)>

In [154]:
#Training Segment: k nearest neighbor
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [155]:
#Pass compressed matrix to train
model.fit(games_sparse_mx)

NearestNeighbors(algorithm='brute')

In [156]:
#distance, reccomendation = model.kneighbors(games_pivot_table.iloc[52, :].values.reshape(1, -1), n_neighbors=10)

In [157]:
#distance

In [158]:
#reccomendation

In [159]:
#for i in range(len(reccomendation)):
 #   print(games_pivot_table.index[reccomendation[i]])

In [160]:
def reccomend_games(game_name):
    game_id = np.where(games_pivot_table.index == game_name)[0][0]
    distance, reccomendation = model.kneighbors(games_pivot_table.iloc[game_id, :].values.reshape(1, -1), n_neighbors=10)

    for i in range(len(reccomendation)):
        games = games_pivot_table.index[reccomendation[i]]
        for j in games:
            print(j)

In [163]:
#reccomend_games('"Revenge Of Heroes"')

"Revenge Of Heroes"
"Bounce Blast" Construct 3 Template
123 Soleil!
"Optical illusion"
20 000 pieds sous terre
111 Winchester: From Song to Story
2 Minutes for Roughing
4 Games
4 & Balls
10000000

In [ ]:
print("Disclaimer: The games list is very large, So I made the look up feature to display only as many rows as you want")
while True:
    print("Please enter a choice: ")
    print("1: Look up Games list to find a game from the catalog")
    print("2: Enter a game name and get a set of reccomendations")
    print("3. Exit Program")
    inputVal = int(input("Enter Choice: "))
    print("")

    gameVal = 0
    
    if inputVal == 1:
        valueNum = int(input("How many Values would you like to display?: "))
        print("GAME CATALOG")
        arr = games_pivot_table.head(valueNum)
        arr.reset_index()
        print(arr.loc[: ,1])
        #gameVal = int(input("Type the Number ID of the game you wnat to search: "))
        #gameName = games_pivot_table['name'][gameVal]
        #print("Game You chose: ", gameName)
        print("RECCOMENDED GAMES")
        reccomend_games("20 000 pieds sous terre")
    else:
        break

Disclaimer: The games list is very large, So I made the look up feature to display only as many rows as you want
Please enter a choice:
1: Look up Games list to find a game from the catalog
2: Enter a game name and get a set of reccomendations
3. Exit Program

Enter Choice:  1

How many Values would you like to display?:  12

GAME CATALOG
name
"Bounce Blast" Construct 3 Template    0.0
"Optical illusion"                     0.0
"Revenge Of Heroes"                    0.0
/reroll                                0.0
10000000                               0.0
111 Winchester: From Song to Story     0.0
123 Soleil!                            0.0
2 Minutes for Roughing                 0.0
20 000 pieds sous terre                0.0
4 & Balls                              0.0
4 Games                                0.0
42 Lightyears                          0.0
Name: 1, dtype: float64
RECCOMENDED GAMES
111 Winchester: From Song to Story
10000000
123 Soleil!
"Optical illusion"
20 000 pieds sous terre
4 & Balls
2 Minutes for Roughing
42 Lightyears
4 Games
"Bounce Blast" Construct 3 Template
Please enter a choice:
1: Look up Games list to find a game from the catalog
2: Enter a game name and get a set of reccomendations
3. Exit Program